// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: lvgl_demo

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_Screen2);
    lv_obj_set_width(ui_Keyboard1, 150);
    lv_obj_set_height(ui_Keyboard1, 70);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_TOP_MID);

    ui_TextArea1 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextArea1, 120);
    lv_obj_set_height(ui_TextArea1, 50);
    lv_obj_set_x(ui_TextArea1, 5);
    lv_obj_set_y(ui_TextArea1, -5);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_BOTTOM_LEFT);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");



    ui_Button2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button2, 25);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, -5);
    lv_obj_set_y(ui_Button2, -5);
    lv_obj_set_align(ui_Button2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}
